[package]
name = "game_sp"
version = "0.1.0"
authors = ["C. Jeremiah Schneider <cjschneider2@gmail.com>"]

[dependencies.core_compat]
path = "../core_compat"

[dependencies.rusqlite]
version = "0.11"
features = ["bundled", "blob"]

[dependencies]
sdl2 = "*"